# Generated by Django 5.2.5 on 2025-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_events',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.event'),
        ),
    ]
